### ISSUE TITLE
Ignore CC recipients when language is different from the one of TO recipients

### ISSUE THREAD

**Issue by Angelo-Mascaro** [beltrachi/automatic_dictionary#12]
Hi there. Your idea is great.
I was wondering about something like that since  6-7 years ago. In my mind I was thinking to a field in the address book.

I come with a suggestion for you. I use to write emails in different languages and sometimes I use different languages with the same people :-( 
Normally in these cases the people are in CC and they receive the messages in the language of the TO people. So my suggestion is "not to modify the language of the CC recipients".

Example:
recip-A normally receives emails in Italian
recpi-B  normally receives emails in English
now if I write in English TO recpi-B and CC recip-A, the language for recip-A is modified (and stored) from Italian to English. It would be better keep Italian for recip-A since he is in CC and receives the message in the language of recip-B just in this case.

Thank you very much and kind regards
Angelo

**Comment by beltrachi** [comment]
Is it possible that the rec_B didn't have lang_B assigned but AD said "Guessed lang_B" in the first place?

When the plugin guesses a language, it does not write it down anywhere the mapping rec_B => lang_B. It tries to guess it based on the most frequent language on that domain (@gmail.com => 'en_GB', @lastampa.it => 'it_IT', etc).
But, when you have rec_B in CC of a mail, and assign the lang_A to the mail, it stores lang_A for rec_A and for rec_B UNLESS rec_B had a previous specific lang.

Summarizing, the case you explain can happen when the rec_B is a guess and not a "Remember". Once you store rec_B => lang_B it will not fail any more :)

If you want I have a debugging version of the plugin that registers the activity and I'll be able to see what is happening behind the scenes.

The version with this feature is here https://github.com/beltrachi/automatic_dictionary/raw/v1.7.0/automatic_dictionary.xpi (its not officialy released yet) and do the following:
1. Go to preferences of the plugin (in Thunderbird > Addons > Automatic Dictionary > Preferences)
2. Activate "Save log to file"
3. Set Log level to "Debug"
4. Restart thunderbird
5. Reproduce the case that do not work.
6. Close Thunderbird and open it again.
7. Go to Automatic Dictionary preferences and click on "Send log to developer"
8. After that, disable the "Save to log file" and set Log level back to "Warning".

With that log, I'll have more information and may be able to see what's happening.

**Comment by beltrachi** [comment]
Hi Angelo.

I'm closing this issue. We can reopen it if you are still affected by this.
