### ISSUE TITLE
New release for Thunderbird 100

### ISSUE THREAD

**Issue by Mte90** [beltrachi/automatic_dictionary#128]
I saw that the version supported changed but is not available on https://addons.thunderbird.net/en-US/thunderbird/addon/automatic-dictionary-switching/?src=search for 100 version.
It is possible to do a new release?

**Comment by beltrachi** [comment]
Hi @Mte90 thanks for reporting.

I've sent a new version v3.0.1 and has already been approved by Thunderbird that should be compatible with TB up to v102.0.
You can find it here: https://addons.thunderbird.net/en-US/thunderbird/addon/automatic-dictionary-switching/versions/?page=1#version-3.0.1

Best

**Comment by Mte90** [comment]
perfect thanks!
