### ISSUE TITLE
SpellCheck not working after email account change

### ISSUE THREAD

**Issue by Michael-E-Rose** [beltrachi/automatic_dictionary#15]
Using TB 31.7.0 on Ubuntu 14.04, I recently changed my email account (both gmail). Automatic dictionary switcher was working perfectly on the first account, but as soon as I deleted the account, and added the new account, it stopped working: I don't see any notification about saved settings when composing a message. Re-installation doesn't help.

**Comment by beltrachi** [comment]
Hi Michael,

does appear any message on the Error console? Could you paste it here?

The error console is in Tools > Error console (Shift + Ctrl + j)

**Comment by Michael-E-Rose** [comment]
This morning, I reinstalled Thunderbird (thereby deleting all plugins). Therefore I am very sorry, but I can't replicate the error any more.

**Comment by beltrachi** [comment]
No problem. Glad to hear it! Closing it then. Thanks!
