### ISSUE TITLE
Change language without updating users if more than one

### ISSUE THREAD

**Issue by leopoldog** [beltrachi/automatic_dictionary#16]
Hi,

if I select many contacts that use different languages, I have to select english to write to them.
The change of language updates all the selected users and this is very annoying because normally I want write to each in other languages than english.

I've set the "Max recipients to process per mail" to 1 but making that it's impossible to change the language of the e-mail if he has more than one recipient. Even selecting another language the editor restores every time the language of the first recipient.

It's better to allow the change of the language even if I have more than one recipient but to not update the user language for all the recipients.

**Comment by beltrachi** [comment]
Hi,

I'll need more data to be able to reproduce your bug.
The plugin is designed to not update values when they have been assigned to a single user so I need more info on how to reproduce it.

You can send me the detailed description steps or activate the logs and send me the log as I describe:
Go to preferences of the plugin (in Thunderbird > Addons > Automatic Dictionary > Preferences)
2. Activate "Save log to file"
3. Set Log level to "Debug"
4. Restart thunderbird
5. Reproduce the case that do not work.
6. Close Thunderbird and open it again.
7. Go to Automatic Dictionary preferences and click on "Send log to developer"
8. After that, disable the "Save to log file" and set Log level back to "Warning".

Thanks!
