### ISSUE TITLE
1.8.2: Confusing message when setting language for two recipients

### ISSUE THREAD

**Issue by jorgk3** [beltrachi/automatic_dictionary#18]
With max recipients set to 2, compose a message to two recipients which don't have a saved language. Set the language. Message received: Saved <dict> as default for 4 recipients.

**Comment by beltrachi** [comment]
Hi Jorgk3,

I'm not able to reproduce it saying 4 recipients. It says 3 at most.

Anyway, the number is the total new combinations stored. I have a branch where I change the message here: https://github.com/beltrachi/automatic_dictionary/commit/6b0194807f26c3836d45c256b5d83b3261572b79

Could you give me the translation for german?

For the "4 recipients" message, I'd need the logs of the plugin to see what is happening behind scenes. Could you send me it?

**Comment by jorgk3** [comment]
The "4 recipients" message only happened in beta versions of 1.8.x. I don't see it in the beta of 1.9.0.

**Comment by jorgk3** [comment]
Will be fixed in 1.9.x.
