### ISSUE TITLE
Ready for TB 115?

### ISSUE THREAD

**Issue by elhennig** [beltrachi/automatic_dictionary#193]
Is there a plan to also make this add-on available on Thunderbird 115,1? I recieved that version in my OS update and updating Auto-Dictionary fails as it is only configured for 115.0, yet

**Comment by yennor** [comment]
same question here ;-).
there seem to be some commits for 115, but nothing releases yet...

**Comment by beltrachi** [comment]
Hey!

Thunderbird v115.1 was released, and the addon only reached 115.0.

I've already submitted the new version compatible with Thunderbird up to 117 (beta). Thunderbird team will approve it soon. I'll ping you once it happens.

Thanks for reporting!! And for using the addon, of course!

**Comment by beltrachi** [comment]
@elhennig @yennor These people are fast! You have the new version already available!

https://addons.thunderbird.net/en-US/thunderbird/addon/automatic-dictionary-switching/versions/?page=1#version-3.2.4

Enjoy!

**Comment by yennor** [comment]
thanks a lot :-)
