### ISSUE TITLE
Guessing

### ISSUE THREAD

**Issue by jorgk3** [beltrachi/automatic_dictionary#21]
When you guess the language, it's not stored. So the next time the user writes to the same recipient, you guess again. Why?

If you guessed correctly, that is, the user doesn't change the guess, you can store it. If the user changes the guess, you will store that anyway. Conclusion: You can always securely store the guess.

**Comment by orschiro** [comment]
Dear all, 

I think this is the feature I was looking for, too. 

If you write someone for the first time, then it would be great if the add-on could auto-detect the written language and thus switch the dictionary. 

If the user then doesn't change it manually to another language, this language could be stored as the default one for that contact, correct?

Warmly,

-Robert

**Comment by beltrachi** [comment]
You are right, this is a good feature. I didn't see the benefit at first but realized that this affects next guessings increasing the weight of the language just guessed.
 
I've prepared a beta version with this behavior. Would you mind to give it a try?
You can download it from here: https://github.com/beltrachi/automatic_dictionary/raw/store-guessings/automatic_dictionary.xpi

**Comment by orschiro** [comment]
Thank you for your work, @beltrachi!

-Robert

![image](https://cloud.githubusercontent.com/assets/170947/18910605/13c9c332-8579-11e6-9fd8-adb1e107c8ec.png)

**Comment by beltrachi** [comment]
@orschiro It looks for the most frequent language on "mail.de" first. If it has no data, it will look for ".de" to get the most probable.

Why were you expecting it to be English? It does not detect based on email body.

**Comment by orschiro** [comment]
It does not detect based on email body.

This would be a nice feature. Possible? :-)

-Robert

**Comment by beltrachi** [comment]
Nope, sorry.

You can install other extensions that do that, like https://addons.mozilla.org/en-Us/thunderbird/addon/dictionary-switcher/

I want to keep this extension simple.

**Comment by orschiro** [comment]
Perfect, thanks for the recommendation!

**Comment by eMPee584** [comment]
>> detect based on email body […] would be a nice feature. Possible? :-)

> Nope, sorry. […] I want to keep this extension simple.
But then, the name of the extension is very misleading. It does not at all suggest that the automatism is based purely on per-sender/domain statistics collected after manually switching language for every single email.
I to a large number of recipients (usually once each), alternating between DE and EN. This is presumably a common work flow for people who are looking for an "automatic dictionary switcher".
But anyway, back to the technical side. I think there's an easy technical solution to integrate:
https://github.com/richtr/guessLanguage.js

**Comment by beltrachi** [comment]
@eMPee584 Thanks for the technical solution. It's interesting. I knew this existed but haven't looked for a nodejs implementation.

I'm sorry but I have no interest on doing things others have already done unless I have something to improve. You have this extension https://addons.mozilla.org/en-Us/thunderbird/addon/dictionary-switcher/ which does detect the language based on what you write.

If you think this feature is worth it, feel free to create a pull request with the feature and I'll be more than happy to review and integrate it. Any collaboration will be more than welcome.

The naming could be improved, I totally agree. Any suggestion?

**Comment by B00ze64** [comment]
@beltrachi Good day.

The extension you are referring to (Dictionary Switcher) does not work on any recent version of Thunderbird (it wasn't working on TB24, when I tested it). There used to be other extensions that did this as well (Markov Dictionary Switcher and Smart Dictionary Switcher) but they did not work in TB24 either. The problem with all these extensions is that the way dictionaries are "known" in TB has changed since the extensions were written - they no longer detect the installed dictionaries.

What people are suggesting however means you would just have to re-write your extension - What is the purpose of storing language preference by recipient if you can detect language automatically? Might as well never store anything and just always detect as the user types the email.

Maybe you could pick-up one of these old extensions and fix them? The Markov one looks good, since it is apparently 1000 times faster than the original Dictionary Switcher...

Regards,

**Comment by Johann-Tree** [comment]
Is it possible to switch off guessing on domain or TLD?
95% of all my emails I write in German, only 5% in English. So I would like to only store the recipients I write in English. At the moment all gmail.com contacts will be guessed as English language and I have to change that manually.

**Comment by beltrachi** [comment]
@B00ze64 Hi!

I'm sorry that the other extensions don't work any more.

Each extension has a different approach and there is no best fit for all users. It depends on your needs. I needed something to remember the preference and I did it. In my approach of not autodetecting by email content, it's useful when you start writing in the wrong language to a known recipient.

I'm not going to fix other's extensions, I'm sorry. Maybe you can ask for this on Thunderbird forums like this: https://discourse.mozilla-community.org/c/add-ons

Thunderbird and Firefox codebases are diverging over time, so its perfectly possible to work on Firefox but not on Thunderbird.

Have you considered using an old Thunderbird version?

**Comment by beltrachi** [comment]
@Johann-Tree Hi!

It's not possible to switch off guessing by TLD. 

But with the extension as is, it will be useful for 95% of the cases isn't it?
The guessing logic will detect that you use German for most gmail.com users and set German by default. Or at least that's what it's supposed to do.

The guessing does not pretend to be 100% perfect, but to avoid you to change every time. If you are writing to foo@gmail.com and switch to english, it will remember it forever. No matter what the guessing says.

**Comment by beltrachi** [comment]
I'm closing this issue because original feature was developed and released.

To request other features open anoter ticket. 

I'm not going to work on this extension any more except to fix issues. 

You can create issues and maybe some developer can work on it. Any collaboration will be more than welcome.
