### ISSUE TITLE
Thunderbird 52.0

### ISSUE THREAD

**Issue by bonanza123** [beltrachi/automatic_dictionary#23]
Is it possible that the addons stopped working on Thunderbird 52.0? I don't get any response from it when changing the dictionary for a recipient. Moreover, when I go into the settings of the extensions and enable "Save log to file" and restart Thunderbird, compose some messages, and then go back to the extension settings and click "Send log file to dev" nothing happens.

Unfortunately, I was also not able to get the logs from the error console of thunderbird.

**Comment by beltrachi** [comment]
Thank you for opening this bug and trying to get a log!

I'm aware of this bug since some days ago. The extension requires things that are not there any more, this is why it fails completely.
I'll try to release a fix this week or next.

I'll keep you posted.

**Comment by beltrachi** [comment]
@bonanza123 I've just published the new version but the queue says there are 250 validations before this one, so it can last some days.
You can install the new version from here if you want: https://github.com/beltrachi/automatic_dictionary/raw/master/automatic_dictionary.xpi

Regards!
