### ISSUE TITLE
Automatic Dictionary add-on breaks TB 56.0b1

### ISSUE THREAD

**Issue by tibitts** [beltrachi/automatic_dictionary#25]
I received the automatic update to TB 56.0b1 yesterday.
Upon restart TB came up with the UI completely screwed and unusable.
What still did work was to get into safe mode. I nailed down the problem
to the Automatic Dictionary add-on.
Happens on both, Linux and Windows.

**Comment by beltrachi** [comment]
@tibitts reproduced and looking into it.
Thanks for reporting!!

**Comment by beltrachi** [comment]
AMO team just approved the new version. You can update it and the issue will be fixed.
Best regards!
