### ISSUE TITLE
Firefox support?

### ISSUE THREAD

**Issue by orschiro** [beltrachi/automatic_dictionary#27]
Hello all, 

This is such an amazing add-on!

Any chance we can implement automatic dictionary switch support directly into Firefox as well? :-)

**Comment by beltrachi** [comment]
Hi!

sorry but Firefox has no recipients email addresses to which map a language, as this addon does.

You'll have to look for another addon, sorry. Good luck!

**Comment by orschiro** [comment]
Thanks!

Could we implement another solution to automatic dict switching in Firefox, inspired by your code?

**Comment by beltrachi** [comment]
I'm not working in this addon any more, besides bug fixing and compatibility with new thunderbird versions. Sorry.

But anyone can use the code to do whatever they want. It's MIT license :smile:
