### ISSUE TITLE
TB 57.0b2 compatibility

### ISSUE THREAD

**Issue by vasykiki** [beltrachi/automatic_dictionary#28]
Hello, 
your Automatic dictionary addon, v1.10.1, is very, very useful and worked perfectly, until last Thunderbird 57.0b2 update. Now. at least for me, it does not remember any more the language selections...
Regards, Michael

**Comment by beltrachi** [comment]
You are right, I'm already working on it. I'll keep you posted.

Thanks for reporting!

**Comment by beltrachi** [comment]
@vasykiki I've just submitted a version with the fix and is pending Mozilla revision.

You can install it from here if you want: https://github.com/beltrachi/automatic_dictionary/raw/master/automatic_dictionary.xpi

**Comment by beltrachi** [comment]
Once released the version I'll close this issue.

**Comment by beltrachi** [comment]
Version approved by Mozzilla. Users will be upgraded in the following days.
