### ISSUE TITLE
Recipients not always read when replying

### ISSUE THREAD

**Issue by gergoe** [beltrachi/automatic_dictionary#30]
When replying on messages, almost always the language stays on the default language and not switched to the previously remembered language, whether it's a single recipient or a combination. The database with the address-language combinations are intact, based on the logs of the program it appears it simply cannot read the recipients out of the message.

Attached the log from the add-on, it starts right with the action when I hit the reply button (at 16:31:33) then I wrote an English sentence in the message body which was underlined as not proper Hungarian. Then at 16:31:41 I just clicked into the address field, and that re-triggered the recipient check, found the recipients and set the right language at once. My sentence become correct at once.

![image](https://user-images.githubusercontent.com/9882767/34835657-b70fcfa2-f6f5-11e7-9c92-ee6863344bb3.png)

Sounds like some sort of timing issue, is there no way to put a few ms delay (maybe optional) between opening the email window and reading the recipients?

**Comment by beltrachi** [comment]
Hi @gergoe 

Sorry to hear that. It seems recipients are not set when the plugin looks into them, as you suggest.

Could you provide the following information?

1. Operating system (Windows 7, Mac OS X, ...)
2. Thunderbird version (On thunderbird go to Help > About)
3. Automatic Dictionary version (On Thunderbird > addons)
4. Addons you have enabled, maybe you can send me a screenshot of Thunderbird > Addons window?

I guess the window will emit an event I can listen to have all recipients setted, but I need to reproduce it first.

Thanks!

**Comment by gergoe** [comment]
Thunderbird was 45.8.0, when I went to the About screen and it found an update. After applying it, the version went up to 52.5.2. Quite a jump if you ask me, but no idea why it did not follow the releases until i opened the About screen...

Anyway, after the update I don't seem to have the same problem (Thunderbird feels slower, maybe that little delay is what it needed?), when replying the message opens and the language is switched properly to the saved one.

Thank you for unintentionally forcing me to update ;-)
