### ISSUE TITLE
trigger from window focus failing

### ISSUE THREAD

**Issue by kewlfft** [beltrachi/automatic_dictionary#31]
Thanks for this great app, however there is an issue when it is used together with [Virtual Identity](http://www.absorb.it/virtual-id)
It only recognizes the language at the first e-mail reply after opening a session, the second time it does not activate at all. This is because there is no `[event] window focus` it seems triggered the second time when Virtual Identity is active.
Would you be able to trigger on something else?
It stops after:
```
1517430812369 AutomaticDictionary INFO 2018-01-31T20:33:32.369Z [debug] tos are []
1517430812369 AutomaticDictionary INFO 2018-01-31T20:33:32.369Z [debug] ccss are []
```
While this should be followed by:
```
1517430812399 AutomaticDictionary INFO 2018-01-31T20:33:32.399Z [debug] [event] window focus
1517430812487 AutomaticDictionary INFO 2018-01-31T20:33:32.487Z [debug] [event] window blur
1517430813202 AutomaticDictionary INFO 2018-01-31T20:33:33.202Z [debug] recipients found: ["masked-email-0@domain"]
1517430813204 AutomaticDictionary INFO 2018-01-31T20:33:33.204Z [debug] recipients found: []
```
What I would think is to add a new **setListener** in [compose_window.js,](https://github.com/beltrachi/automatic_dictionary/blob/master/chrome/content/ad/compose_window.js) if for some reason there is no window focus we need to trigger the **deduceLanguage** based on another event. What do you think?
It still triggers if I manually click on the subject for example but it should trigger naturally without clicking I think.

**Comment by beltrachi** [comment]
hi @kewlfft 

I'm glad that you take the time to look into the code ^^

Let's try to add a listener on window init. I've prepared a build with that change. Can you try it?

https://github.com/beltrachi/automatic_dictionary/raw/jb/fix-reply-window/automatic_dictionary.xpi

You can see the change in the branch: https://github.com/beltrachi/automatic_dictionary/compare/jb/fix-reply-window

Could you download and install it manually in your Thunderbird?

Regards,
Jordi

**Comment by kewlfft** [comment]
thanks very much for looking into my request this is very appreciated
I am traveling today but will certainly test the change as soon as i get back home.
looking forward to it.
thanks

**Comment by kewlfft** [comment]
@beltrachi are you going to merge and release this change? thanks

**Comment by beltrachi** [comment]
Hi @kewlfft !

sorry for the delay, github did not notify me when you edited your comment saying that it was working, :disappointed: 

I've submitted the new version to Mozilla team. Once it's approved it will be released gradually to all users. Probably in the next days.

Thank you for improving this plugin! ^^

**Comment by kewlfft** [comment]
No problem I was patiently waiting, many thanks for this change ! I can close the issue I suppose.

**Comment by kewlfft** [comment]
works great thanks
