### ISSUE TITLE
Compatability with TB60 

### ISSUE THREAD

**Issue by bonanza123** [beltrachi/automatic_dictionary#32]
TB 60 (the current beta) reports incompatibility with this awesome plugin.
I'm not sure whether this affects real functionality or is just a heads-up that some compatibility flag needs to be set.

**Comment by beltrachi** [comment]
Thanks for reporting!

I'll take a look shortly.

**Comment by beltrachi** [comment]
@bonanza123 Fix done and pending Mozilla release. Version 1.10.4.

Thank you for reporting!

**Comment by bonanza123** [comment]
Thanks so much!
