### ISSUE TITLE
macOS issues

### ISSUE THREAD

**Issue by Lemoert** [beltrachi/automatic_dictionary#34]
I just installed the Automatic Dictionary in Thunderbird (version 60.2.1 on macOS High Sierra 10.13.6) and clicking "Tools > Add-on preferences > Automatic Dictionary" does not open the preferences (which is why I cannot create a log to illustrate the second and more important issue). Secondly, although the add-on seems to save the settings fine (I get the small notification when changing a language) it does not actually change the language when writing a new message to the same email address. I've tried restarting Thunderbird but the issue remains. Also, is there supposed to be a notification shown when the add-on recognises an address and switches language?

Thanks,
Martin

**Comment by beltrachi** [comment]
Hi Martin!

Yes, when the addon detects that the dictionary for the recipients should be different it shows a notification.

Let's see if we can see what happens...
Can you use the extension and send me the errors that appear in the "Error console"?
It can be opened in "Tools" > "Developer tools" > "Error console".
You can send me a screen capture of it. 

Also, a list of the other extensions installed in your Thunderbird can help me reproduce the problem. Can you attach a screenshot where I can see the extensions and the version?

Thanks for reporting!

**Comment by beltrachi** [comment]
Any update on this issue Martin?
