### ISSUE TITLE
Broken compatibility for TB 60.6.1

### ISSUE THREAD

**Issue by beltrachi** [beltrachi/automatic_dictionary#36]
Build for TB stable is broken since last week:
https://travis-ci.org/beltrachi/automatic_dictionary/jobs/548584032

Latest release is 60.6.1 https://www.thunderbird.net/en-US/thunderbird/60.6.1/releasenotes/
which includes some vulnerability fixes.

**Comment by krabo0om** [comment]
Thank you for developing this addon!
Any ETA for Thunderbird 68 support?

**Comment by beltrachi** [comment]
@krabo0om TB 68 support was implemented in this issue https://github.com/beltrachi/automatic_dictionary/issues/37 yesterday. It's pending Thunderbird team approval. I have no idea on the ETA.

If you are in a hurry you can install the extension from the file, as described here: https://github.com/beltrachi/automatic_dictionary/issues/37#issuecomment-529207472

**Comment by krabo0om** [comment]
Thanks, I did not look at the closed issues.

**Comment by beltrachi** [comment]
Closing issue. I've tested with 60.8.0 and v1.11.0 (last version compatible with TB60) works well.
