### ISSUE TITLE
Broken compatibility for TB 68.0

### ISSUE THREAD

**Issue by mrkazoodle** [beltrachi/automatic_dictionary#37]
Automatic dictionary has been disabled after upgrading to Thunderbird 68. Reason: not compatible.

**Comment by beltrachi** [comment]
Thanks for reporting! Changes on TB68 are pretty big. I'll take a look but it do not seem to be fast.
Hope I can release a fix in a week.

**Comment by kewlfft** [comment]
Thanks for this great addon, according to Thunderbird team

> Thunderbird 68.0 is such a switch and one of the major changes of that release is that extension support will be affected negatively by it. Thunderbird 68.0 will support WebExtensions and the following types of extensions:
>     Restartless add-ons if "minor adjustments" were made by their authors.
>     Non-restartless legacy add-ons using XUL overlays if add-on authors adopted them.

These steps must be followed for conversion: https://developer.thunderbird.net/add-ons/updates
Let us know if you need any help.

**Comment by beltrachi** [comment]
Hi!
the new release is ready :tada: 

I've uploaded it to Thunderbird platform and is pending review. It's 9th on the queue so I hope it will be released soon.

If you can't wait you can download the version from here: https://github.com/beltrachi/automatic_dictionary/blob/master/automatic_dictionary.xpi

Thanks for reporting and your help!

Best regards
Jordi
