### ISSUE TITLE
Not working with TB 73.0b1

### ISSUE THREAD

**Issue by d4niel-P** [beltrachi/automatic_dictionary#38]
It's a great add-on but unfortunately stopped working with beta branch of TB (TB 73.0b1 to be exact).

**Comment by beltrachi** [comment]
Thanks for reporting it.

I've already been looking into it and hope to release a working version
soon.

**Comment by beltrachi** [comment]
Finally could migrate the code to MailExtension. Release is waiting for review by Thunderbird team.
Hope it will be released in the following hours/days.

If you want to manually install it, download the automatic_dictionary.xpi from master here on github.

**Comment by d4niel-P** [comment]
Thanks! Extension updated and works flawlessly on 75.0b2 while composing new emails, but it's a hit and miss while using "Reply".

**Comment by beltrachi** [comment]
Glad to hear it!

Could you create an issue for the reply thing?
