### ISSUE TITLE
Spotty bahaviour when replaying

### ISSUE THREAD

**Issue by d4niel-P** [beltrachi/automatic_dictionary#40]
Add-on works great when creating new e-mail but hardly ever when replaying. I tried to pin point circumstances when it works or doesn't but I couldn't find any specific conditions.

**Comment by beltrachi** [comment]
Hi @d4niel-P , could you provide more information? Mainly which versions of each software are you using. It's descirbed here https://github.com/beltrachi/automatic_dictionary#bug-reporting

**Comment by beltrachi** [comment]
@d4niel-P issue solved in release 2.0.1.

Best!

**Comment by d4niel-P** [comment]
Thank you! I'll test it asap.
