### ISSUE TITLE
Add-on does not work with Thunderbird version 78.4.3

### ISSUE THREAD

**Issue by hendriksi** [beltrachi/automatic_dictionary#64]
After the last update of Thunderbird to version 78.x the add-on has stopped working.
Thunderbird says that this add-on is not compatible with the current version of Thunderbird.

![Screenshot 2020-11-12 11 03 57](https://user-images.githubusercontent.com/9208996/98927352-b7caf700-24d8-11eb-8a62-d4e7f40a85ec.png)

## Context (Environment)
Thunderbird version 78.4.3
Win 10 Pro

**Comment by beltrachi** [comment]
Hi @hendriksi 

the plugin you have installed is an older version. You need to upgrade the plugin version. Could you check if there is any option in the Addons tab to "Check for updates"? That may fix your issue.

**Comment by hendriksi** [comment]
Unfortunately, the update did not work in Thunderbird. I have removed the add-on and installed the new version manually. Now it works well.
Many thanks for your help and this great tool.

**Comment by louisgag** [comment]
Thanks @hendriksi for pointing out this issue: I also had to remove and re-install.
And thanks @beltrachi for this really useful plugin!
