### ISSUE TITLE
Spell Checking stop working

### ISSUE THREAD

**Issue by thePanz** [beltrachi/automatic_dictionary#8]
Under TB  24.0.0 and extension release 1.5.0 spell checking stops working (intermittent).
I'm investigating with release 1.5.4 (found in another issue)

**Comment by beltrachi** [comment]
@thePanz any update on this issue?

**Comment by thePanz** [comment]
I've updated to TB 38.0.1 but didn't notice any issue so far..
This issue is now 2yr old now, with tons of new TB releases in the while! :)
I guess we should close this issue.. or not?

**Comment by beltrachi** [comment]
Of course! Closing it.
